name: Build images from latest dev branch

on:
  push:
    branches:
      - main

jobs:
  create-dev-image:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Log in to docker registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password-stdin

      - name: Build new images and push
        run: |
          make \
            build-docker-images \
            push-docker-images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # webapp
          PORT: 80
          REACT_APP_TAG: ${{ github.ref }}
          REACT_APP_NAME: 'wax_boilerplate'
          REACT_APP_TITLE: 'WAX Fullstack Boilerplate'
          REACT_APP_LOGO: 'https://raw.githubusercontent.com/eoscostarica/design-assets/master/logos/eosCR/fullColor-vertiall-transparent-white.png'
          REACT_APP_FOOTER_LINKS: '[]'
          REACT_APP_WAX_APP_NAME: 'WAX Full-Stack Boilerplate'
          REACT_APP_WAX_API_PROTOCOL: 'https'
          REACT_APP_WAX_API_HOST: 'chain.wax.io'
          REACT_APP_WAX_API_PORT: '443'
          REACT_APP_WAX_CHAIN_ID: '1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4'
          REACT_APP_HASURA_URL: 'https://graphql-wax-boilerplate.eosio.cr/v1/graphql'

      - name: Build kubernetes files
        id: build_kubernetes_files
        run: |
          make \
            build-kubernetes
        env:
          # general
          NAMESPACE: wax-boilerplate
          INGRESS_HOST: wax-boilerplate.eosio.cr
          INGRESS_GRAPHQL_HOST: graphql-wax-boilerplate.eosio.cr
          # Postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_DATA: ${{ secrets.POSTGRES_DATA }}
          # hapi
          HAPI_SERVER_PORT: 9090
          HAPI_SERVER_ADDRESS: 0.0.0.0
          HAPI_NETWORK_API: 'https://chain.wax.io'
          HAPI_NETWORK_CHAIN_ID: '1064487b3cd1a897ce03ae5b6a865651747e2e152090f99c1d19d44e01aea5a4'
          HAPI_NETWORK_BASE_ACCOUNT: ${{ secrets.HAPI_NETWORK_BASE_ACCOUNT }}
          HAPI_NETWORK_BASE_PASSWORD: ${{ secrets.HAPI_NETWORK_BASE_PASSWORD }}
          HAPI_NETWORK_WALLET_URL: ${{ secrets.HAPI_NETWORK_WALLET }}
          HAPI_HASURA_URL: ${{ secrets.HAPI_HASURA_URL }}
          HAPI_HASURA_ADMIN_SECRET: ${{ secrets.HAPI_HASURA_ADMIN_SECRET }}
          # hasura
          HASURA_GRAPHQL_ENABLE_CONSOLE: true
          HASURA_GRAPHQL_DATABASE_URL: ${{ secrets.HASURA_GRAPHQL_DATABASE_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${{ secrets.HASURA_GRAPHQL_UNAUTHORIZED_ROLE }}
          HASURA_GRAPHQL_ACTION_BASE_URL: ${{ secrets.HASURA_GRAPHQL_ACTION_BASE_URL }}

      - name: Deploy kubernetes files
        uses: steebchen/kubectl@v1.1.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          NAMESPACE: wax-boilerplate
          K8S_BUILD_DIR: build_k8s
        with:
          args: version && make deploy-kubernetes
